import React, { useState } from "react";
import { Plus, X } from "lucide-react";
import type { Plugin } from "../../types";

interface ImportModalProps {
	onClose: () => void;
	onImport: (plugin: Plugin) => void;
}

export const ImportModal: React.FC<ImportModalProps> = ({
	onClose,
	onImport,
}) => {
	const [importJson, setImportJson] = useState("");

	const handleImport = () => {
		try {
			const newPlugin = JSON.parse(importJson);
			if (
				!newPlugin.id ||
				!newPlugin.name ||
				!Array.isArray(newPlugin.sections)
			) {
				alert("Invalid Plugin Format");
				return;
			}
			onImport(newPlugin);
			setImportJson("");
			onClose();
		} catch (e: any) {
			alert("Invalid JSON: " + e.message);
		}
	};

	return (
		<div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
			<div className="bg-white dark:bg-slate-900 rounded-xl shadow-2xl w-full max-w-2xl flex flex-col max-h-[90vh] ring-1 ring-slate-200 dark:ring-slate-800">
				<div className="p-6 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center">
					<h2 className="text-xl font-bold flex items-center gap-2">
						<Plus className="w-5 h-5 text-blue-500" />
						Import Plugin
					</h2>
					<button
						onClick={onClose}
						className="text-slate-500 hover:text-slate-700"
					>
						<X size={24} />
					</button>
				</div>

				<div className="p-6 flex-1 overflow-hidden flex flex-col">
					<p className="text-sm text-slate-500 mb-4">
						Paste the JSON generated by your conversion script here.
					</p>
					<textarea
						value={importJson}
						onChange={(e) => setImportJson(e.target.value)}
						placeholder='{"id": "rust-std", "name": "Rust Standard Library", ...}'
						className="flex-1 w-full p-4 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-700 rounded-lg font-mono text-xs focus:ring-2 focus:ring-blue-500 outline-none resize-none leading-relaxed"
					/>
				</div>

				<div className="p-6 border-t border-slate-200 dark:border-slate-800 flex justify-end gap-3 bg-slate-50/50 dark:bg-slate-900/50">
					<button
						onClick={onClose}
						className="px-4 py-2 text-slate-600 hover:bg-slate-200 dark:hover:bg-slate-800 rounded-lg transition-colors"
					>
						Cancel
					</button>
					<button
						onClick={handleImport}
						className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium shadow-lg shadow-blue-500/20 transition-all active:scale-95"
					>
						Load Plugin
					</button>
				</div>
			</div>
		</div>
	);
};
